#!/usr/bin/env node
/**
 * generate_theme_css.mjs — ABDScope theme cascade generator
 *
 * Produces ABDScope/WebUI/src/theme.generated.css from the canonical sources:
 *   - ABDSharedAssets/styles/themes/*.css  (host palettes)
 *   - ABDSharedAssets/styles/components/scope.css  (module→host adapter)
 *
 * The generated file is committed alongside the module so the embedded
 * binary-data WebUI stays self-contained
 * (nothing is read from disk at runtime).
 * Kept in sync by WebUI/tests/theme.test.js.
 *
 * Resolved paths:
 *   ROOT            — workspace root with ABDSharedAssets/ beside ABDScope/
 *   SCOPE_WEBUI     — ABDScope/WebUI
 *   SCOPE_SRC       — ABDScope/WebUI/src
 *   OUT_PATH        — ABDScope/WebUI/src/theme.generated.css
 *   THEMES_DIR      — ABDSharedAssets/styles/themes
 *   ADAPTER_PATH    — ABDSharedAssets/styles/components/scope.css
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

function resolveRoot() {
  const argv = process.argv;
  const explicit = argv.find((a) => !a.startsWith('--') && /ABDSharedAssets/.test(a));
  if (explicit) {
    const p = resolve(explicit);
    if (existsSync(p)) return resolve(p, '..');
  }

  const cwd = process.cwd();
  const dot = resolve(cwd, 'ABDSharedAssets');
  if (existsSync(dot)) return cwd;

  const parent = resolve(cwd, '..');
  const sibling = resolve(parent, 'ABDSharedAssets');
  if (existsSync(sibling)) return parent;

  const cwdAlt = join(cwd, 'ABDSharedAssets');
  if (existsSync(cwdAlt)) return cwd;

  const fallback = resolve(HERE, '..');
  const fb = resolve(fallback, 'ABDSharedAssets');
  if (existsSync(fb)) return fallback;

  throw new Error(
    [
      'No se encuentra ABDSharedAssets desde el workspace actual.',
      'Este script espera ejecutarse desde la raíz del workspace',
      '(donde existe ABDSharedAssets/ y ABDScope/), o bien pasar la ruta',
      'base explícita como primer argumento no opcional.',
      '',
      `cwd actual: ${cwd}`,
    ].join('\n')
  );
}

const ROOT = resolveRoot();
const SCOPE_DIR = join(ROOT, 'ABDScope');
const SCOPE_WEBUI = join(SCOPE_DIR, 'WebUI');
const SCOPE_SRC = join(SCOPE_WEBUI, 'src');

const ABS_ASSETS = join(ROOT, 'ABDSharedAssets');
const THEMES_DIR = join(ABS_ASSETS, 'styles', 'themes');
const ADAPTER_PATH = join(ABS_ASSETS, 'styles', 'components', 'scope.css');

const OUT_PATH = join(SCOPE_SRC, 'theme.generated.css');

const normalize = (css) => css.replace(/^\uFEFF/, '').replace(/\r/g, '').trim();

function readCanonical() {
  if (!existsSync(ABS_ASSETS)) {
    throw new Error(`ABDSharedAssets no está en el workspace: ${ABS_ASSETS}`);
  }
  if (!existsSync(THEMES_DIR)) {
    throw new Error(`ABDSharedAssets/styles/themes no está: ${THEMES_DIR}`);
  }
  if (!existsSync(ADAPTER_PATH)) {
    throw new Error(`El adaptador no está: ${ADAPTER_PATH}`);
  }

  const themeFiles = readdirSync(THEMES_DIR)
    .filter((f) => f.endsWith('.css'))
    .sort();

  const themes = themeFiles.map((f) => {
    const raw = readFileSync(join(THEMES_DIR, f), 'utf8');
    return { file: f.replace(/\.css$/, ''), css: normalize(raw) };
  });

  const adapterRaw = readFileSync(ADAPTER_PATH, 'utf8');
  const adapter = normalize(adapterRaw);

  return { themes, adapter };
}

function buildGenerated({ themes, adapter }) {
  const header = [
    '/**',
    ' * ABDScope Theme Cascade (generated)',
    ' * ===============================',
    ' * Host-driven theme palettes, generated at development time from',
    ' * ABDSharedAssets/styles/themes/*.css plus the component adapter',
    ' * ABDSharedAssets/styles/components/scope.css.',
    ' *',
    ' * Commited alongside el módulo: the embedded binary-data WebUI',
    ' * loads this static file and never reads from disk at runtime.',
    ' *',
    ' * Generated by: tools/generate_theme_css.mjs',
    ' * Sync guard:   WebUI/tests/theme.test.js',
    ' */',
    '',
  ].join('\n');

  const themeBlocks = themes.map(({ file, css }) => {
    return [
      `/* ── theme: ${file} ── */`,
      `/* canonical: ABDSharedAssets/styles/themes/${file}.css */`,
      css,
      '',
    ].join('\n');
  });

  const adapterComment = [
    '/* ── adapter: module tokens → host tokens ── */',
    '/* canonical: ABDSharedAssets/styles/components/scope.css */',
    adapter,
    '',
  ].join('\n');

  return header + themeBlocks.join('\n') + adapterComment;
}

function main() {
  const canon = readCanonical();
  const generated = buildGenerated(canon);

  mkdirSync(SCOPE_SRC, { recursive: true });
  writeFileSync(OUT_PATH, generated, 'utf8');

  console.log(`generated ${OUT_PATH}`);
  console.log(`  themes: ${canon.themes.length}`);
  console.log(`    ${canon.themes.map((t) => t.file).join(', ')}`);
}

main();
